### ISSUE TITLE
Need permission to control access to project list page

### ISSUE THREAD

**Issue by minorOffense** [coldfrontlabs/fserver#23]
FServer UI menu to get to the project directory should have a permission assigned to the menu item so we can control access.

**Comment by minorOffense** [comment]
![screen shot 2014-03-12 at 10 05 18 am](https://f.cloud.github.com/assets/871728/2397908/e1890a16-a9ef-11e3-82bd-9fd7dcb65fcf.png)

**Comment by ClassicCut** [comment]
see commit https://github.com/coldfrontlabs/fserver/commit/c5af4f157cb074a5e74916e134f0640b75fb23d9

I added a permissions check on the view.
