### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by fugazi73** [coldfrontlabs/fserver#25]
with the installation I get the database error. Can anyone help me?

 in db_create_table() (line 2717 of
/includes/database/database.inc).
Cannot modify header information - headers already sent by (output started at                                      [warning]
/drush/includes/output.inc:37) bootstrap.inc:1217
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#039;DEFAULT NULL,
`supported_majors` VARCHAR(255) NOT NULL DEFAULT &#039;&#039; COMMENT &#039;Text&#039; at line 6: CREATE TABLE {eck_project} (
`id` INT NOT NULL auto_increment COMMENT &#039;The primary identifier for a(n) project.&#039;,
`type` VARCHAR(255) NOT NULL DEFAULT &#039;&#039; COMMENT &#039;The bundle of the entity&#039;,
`title` VARCHAR(255) NOT NULL DEFAULT &#039;&#039; COMMENT &#039;Text&#039;,
`short_name` VARCHAR(255) NOT NULL DEFAULT &#039;&#039; COMMENT &#039;Text&#039;,
`recommended_major`  DEFAULT NULL,
`supported_majors` VARCHAR(255) NOT NULL DEFAULT &#039;&#039; COMMENT &#039;Text&#039;,
`link` VARCHAR(255) NOT NULL DEFAULT &#039;&#039; COMMENT &#039;Text&#039;,
`project_status` VARCHAR(255) NOT NULL DEFAULT &#039;&#039; COMMENT &#039;Text&#039;,
PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COMMENT &#039;The base table for a(n) project.&#039;; Array
(
)
 in db_create_table() (line 2717 of /includes/database/database.inc).

Best Regards
Patrick

**Comment by minorOffense** [comment]
related to #27 

ECK rc3 has a bug with generating property columns. Once we move away from ECK, this should be resolved.

In the mean time, you can try to use the dev release of ECK, seems to have the patch applied.

**Comment by minorOffense** [comment]
This is definitely fixed.
