### ISSUE TITLE
Database error on enabling modules in Drupal 7.28

### ISSUE THREAD

**Issue by mccrodp** [coldfrontlabs/fserver#28]
<pre>Notice: Undefined index: type in DatabaseSchema_mysql->processField() (line 205 of /Applications/AMPPS/www/local.fserver.an-nai.jp/includes/database/mysql/schema.inc).
Notice: Undefined index: :normal in DatabaseSchema_mysql->processField() (line 205 of /Applications/AMPPS/www/local.fserver.an-nai.jp/includes/database/mysql/schema.inc).
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DEFAULT NULL, `supported_majors` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Text' at line 7: CREATE TABLE {eck_project} ( `id` INT NOT NULL auto_increment COMMENT 'The primary identifier for a(n) project.', `type` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'The bundle of the entity', `title` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Text', `uuid` CHAR(36) NOT NULL DEFAULT '' COMMENT 'The Universally Unique Identifier.', `short_name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Text', `recommended_major` DEFAULT NULL, `supported_majors` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Text', `link` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Text', `project_status` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Text', PRIMARY KEY (`id`) ) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COMMENT 'The base table for a(n) project.'; Array ( ) in db_create_table() (line 2720 of /Applications/AMPPS/www/local.fserver.an-nai.jp/includes/database/database.inc).</pre>

Hi,

I am encountering the database error above with Drupal 7.28, installed with the standard profile. The makefile used for the version of Drupal and modules I am using is below.

<pre>; ----------------
; Generated makefile from http://drushmake.me
; Permanent URL: http://drushmake.me/file.php?token=b63b7b580d0a
; ----------------
;
; This is a working makefile - try it! Any line starting with a `;` is a comment.
  
; Core version
; ------------
; Each makefile should begin by declaring the core version of Drupal that all
; projects should be compatible with.
  
core = 7.x
  
; API version
; ------------
; Every makefile needs to declare its Drush Make API version. This version of
; drush make uses API version `2`.
  
api = 2
  
; Core project
; ------------
; In order for your makefile to generate a full Drupal site, you must include
; a core project. This is usually Drupal core, but you can also specify
; alternative core projects like Pressflow. Note that makefiles included with
; install profiles *should not* include a core project.
  
; Drupal 7.x. Requires the `core` property to be set to 7.x.
projects[drupal][version] = 7.28

  
  
; Modules
; --------
projects[content_access][version] = 1.2-beta2
projects[content_access][type] = "module"
projects[admin_menu][version] = 3.0-rc4
projects[admin_menu][type] = "module"
projects[module_filter][version] = 2.0-alpha2
projects[module_filter][type] = "module"
projects[ctools][version] = 1.4
projects[ctools][type] = "module"
projects[context][version] = 3.2
projects[context][type] = "module"
projects[date][version] = 2.7
projects[date][type] = "module"
projects[devel][version] = 1.5
projects[devel][type] = "module"
projects[features][version] = 2.0
projects[features][type] = "module"
projects[email][version] = 1.3
projects[email][type] = "module"
projects[link][version] = 1.2
projects[link][type] = "module"
projects[advanced_help][version] = 1.1
projects[advanced_help][type] = "module"
projects[better_formats][version] = 1.0-beta1
projects[better_formats][type] = "module"
projects[entity][version] = 1.5
projects[entity][type] = "module"
projects[entityreference][version] = 1.1
projects[entityreference][type] = "module"
projects[field_group][version] = 1.3
projects[field_group][type] = "module"
projects[globalredirect][version] = 1.5
projects[globalredirect][type] = "module"
projects[gmap][version] = 2.9
projects[gmap][type] = "module"
projects[libraries][version] = 2.2
projects[libraries][type] = "module"
projects[location][version] = 3.2
projects[location][type] = "module"
projects[logintoboggan][version] = 1.3
projects[logintoboggan][type] = "module"
projects[login_destination][version] = 1.1
projects[login_destination][type] = "module"
projects[menu_block][version] = 2.4
projects[menu_block][type] = "module"
projects[menu_minipanels][version] = 1.1
projects[menu_minipanels][type] = "module"
projects[pathauto][version] = 1.2
projects[pathauto][type] = "module"
projects[references][version] = 2.1
projects[references][type] = "module"
projects[site_verify][version] = 1.1
projects[site_verify][type] = "module"
projects[strongarm][version] = 2.0
projects[strongarm][type] = "module"
projects[token][version] = 1.5
projects[token][type] = "module"
projects[panels][version] = 3.4
projects[panels][type] = "module"
projects[print][version] = 2.0
projects[print][type] = "module"
projects[rules][version] = 2.7
projects[rules][type] = "module"
projects[ckeditor][version] = 1.14
projects[ckeditor][type] = "module"
projects[views][version] = 3.7
projects[views][type] = "module"
projects[views_bulk_operations][version] = 3.2
projects[views_bulk_operations][type] = "module"
projects[webform][version] = 3.20
projects[webform][type] = "module"
projects[xmlsitemap][version] = 2.0
projects[xmlsitemap][type] = "module"

;Features Server Dependencies
projects[eck][version] = 2.0-rc3
projects[eck][type] = "module"
projects[eck][patch][] = https://gist.githubusercontent.com/minorOffense/cb7b803362bc474e3607/raw/7cf0eaad3ecce52b91a5b3055c6d77fdc42302f5/uuid-eck-2.x.patch
projects[entityreference][version] = 1.1
projects[entityreference][type] = "module"
projects[filehash][version] = 1.3
projects[filehash][type] = "module"
projects[uuid][version] = 1.0-alpha5
projects[uuid][type] = "module"
projects[field_validation][version] = 2.4
projects[field_validation][type] = "module"
projects[url][version] = 1.0
projects[url][type] = "module"
projects[services][version] = 3.7
projects[services][type] = "module"
projects[elements][version] = 1.4
projects[elements][type] = "module"
projects[views_linkarea][version] = 1.0
projects[views_linkarea][type] = "module"
projects[inline_entity_form][version] = 1.5
projects[inline_entity_form][type] = "module"

;Custom FServer code
projects[fserver][type] = "module"
projects[fserver][download][type] = "git"
projects[fserver][download][url]="git://github.com/coldfrontlabs/fserver.git"

; Themes
; --------

  
  
; Libraries
; ---------
; No libraries were included

</pre>

Please let me know if there is something I am missing.

Thank you,
Paul.
- Also, I cannot see where the admin URL to the Feature Server UI is. I've looked in Drupal and in the module.

**Comment by fugazi73** [comment]
Hello mccrodp,

I had to test the same problem https://github.com/coldfrontlabs/fserver/issues/25, after long I could change it with by eck-7.x-2.0-rc3 by eck-7.x-2.x-dev solved.

**Comment by mccrodp** [comment]
Hi fugazi73,

That's great, thanks. I changed the ECK project version line in my make file to <code>projects[eck][version] = 2.x-dev</code>, re-downloaded and reinstalled using the standard profile. I enabled the Feature Server module and it's dependencies. This time the database errors were resolved. I just have one PHP warning upon enabling, but I am unsure which particular module is causing it.

<pre>Warning: array_keys() expects parameter 1 to be array, null given in drupal_schema_fields_sql() (line 7070 of /Applications/AMPPS/www/local.fserver.an-nai.jp/includes/common.inc).
Warning: array_keys() expects parameter 1 to be array, null given in drupal_schema_fields_sql() (line 7070 of /Applications/AMPPS/www/local.fserver.an-nai.jp/includes/common.inc).</pre>

Everything else looks ok so far. 

Many thanks for linking our issues.

Paul.

**Comment by minorOffense** [comment]
The warnings should go away when ECK goes away
