### ISSUE TITLE
Reference to releases does not work

### ISSUE THREAD

**Issue by fugazi73** [coldfrontlabs/fserver#29]
reference to releases does not work. I get no connection to the project or umgekerht. attached screenshots

![26-05-_2014_15-24-35](https://cloud.githubusercontent.com/assets/7265472/3082798/85b831ce-e4d9-11e3-890a-065f0732a667.jpg)
![26-05-_2014_15-25-29](https://cloud.githubusercontent.com/assets/7265472/3082800/85b9b42c-e4d9-11e3-934f-c1083400677c.jpg)
![26-05-_2014_15-25-49](https://cloud.githubusercontent.com/assets/7265472/3082799/85b97a7a-e4d9-11e3-884b-523a2b92cf71.jpg)
![26-05-_2014_15-26-02](https://cloud.githubusercontent.com/assets/7265472/3082802/85ba7448-e4d9-11e3-9230-fa206d071816.jpg)
![26-05-_2014_15-26-14](https://cloud.githubusercontent.com/assets/7265472/3082801/85ba6a2a-e4d9-11e3-8653-077b5ebfd69a.jpg)

**Comment by mccrodp** [comment]
I think I am seeing this error too when using latest version of fserver on gitHub with Drupal 7.28 and ECK dev (2.x-dev+15). When I save the page i get the following errors.

<pre>Notice: Undefined property: fserverRelease::$version_patch in fserverRelease->generateReleaseName() (line 556 of /Applications/AMPPS/www/local.fserver.an-nai.jp/sites/all/modules/fserver/fserver.module).
Notice: Undefined property: fserverRelease::$version_extra in fserverRelease->generateReleaseName() (line 556 of /Applications/AMPPS/www/local.fserver.an-nai.jp/sites/all/modules/fserver/fserver.module).
Notice: Undefined property: fserverRelease::$api in fserverRelease->generateReleaseName() (line 557 of /Applications/AMPPS/www/local.fserver.an-nai.jp/sites/all/modules/fserver/fserver.module).
Notice: Undefined property: fserverRelease::$version_major in fserverRelease->generateReleaseName() (line 557 of /Applications/AMPPS/www/local.fserver.an-nai.jp/sites/all/modules/fserver/fserver.module).
Notice: Undefined property: fserverRelease::$version_patch in fserverRelease->generateReleaseName() (line 557 of /Applications/AMPPS/www/local.fserver.an-nai.jp/sites/all/modules/fserver/fserver.module).
Notice: Undefined property: fserverRelease::$project_short_name in fserverRelease->generateReleaseName() (line 567 of /Applications/AMPPS/www/local.fserver.an-nai.jp/sites/all/modules/fserver/fserver.module).</pre>

**Comment by minorOffense** [comment]
Try upgrading ECK to the latest dev. Also please check the patch has been applied for UUID support (that's a new requirement)

Our ECK dependency is causing us enough issue that we're going to deprecate it over the next few days. Going to write our entities from scratch.

**Comment by minorOffense** [comment]
This should also be fixed.
