### ISSUE TITLE
Unable to edit project and save project page

### ISSUE THREAD

**Issue by minorOffense** [coldfrontlabs/fserver#35]
The following notice appears when you edit a project page, edit the project entity, click "update entity" and then "save" on the project page node.

> The content on this page has either been modified by another user, or you have already submitted modifications using this form. As a result, your changes cannot be saved.

**Comment by ClassicCut** [comment]
I don't think this was a bug with fserver itself.  Issue was in a Dropfort module that modified the project form and submit handlers.
