### ISSUE TITLE
problems with release xml

### ISSUE THREAD

**Issue by ClassicCut** [coldfrontlabs/fserver#37]
There are no stable releases for project dropforty.                                                          [warning]
uasort() expects parameter 1 to be array, null given updatexml.inc:268                                       [warning]
Invalid argument supplied for foreach() updatexml.inc:271                                                    [warning]
Invalid argument supplied for foreach() updatexml.inc:280                                                    [warning]
uasort() expects parameter 1 to be array, null given updatexml.inc:268                                       [warning]
Invalid argument supplied for foreach() updatexml.inc:271                                                    [warning]
Invalid argument supplied for foreach() updatexml.inc:280                                                    [warning]
Choose one of the available releases for dropforty:
 [0]  :  Cancel

**Comment by minorOffense** [comment]
Some other warnings, these are server side

> Notice: Undefined index: project in dropfort_um_load_project_by_site_identifier() (line 820 of /var/www/html/app/profiles/dropfort_profile/modules/custom/dropfort_um/dropfort_um.module).
> Warning: get_class() expects parameter 1 to be object, boolean given in FeatureServerProjectXMLFormatter->render() (line 10 of /var/www/html/app/profiles/dropfort_profile/modules/custom/fserver/fserver_services/fserver_services.inc).
> Notice: Undefined index: project in dropfort_um_load_project_by_site_identifier() (line 820 of /var/www/html/app/profiles/dropfort_profile/modules/custom/dropfort_um/dropfort_um.module).
> Warning: get_class() expects parameter 1 to be object, boolean given in FeatureServerProjectXMLFormatter->render() (line 10 of /var/www/html/app/profiles/dropfort_profile/modules/custom/fserver/fserver_services/fserver_services.inc).
> Warning: get_class() expects parameter 1 to be object, string given in FeatureServerProjectXMLFormatter->render() (line 10 of /var/www/html/app/profiles/dropfort_profile/modules/custom/fserver/fserver_services/fserver_services.inc).
> Warning: Unknown class passed as parameter in FeatureServerProjectXMLFormatter->render() (line 10 of /var/www/html/app/profiles/dropfort_profile/modules/custom/fserver/fserver_services/fserver_services.inc).

**Comment by minorOffense** [comment]
Fixed
