### ISSUE TITLE
Update service warnings messages

### ISSUE THREAD

**Issue by spotzero** [coldfrontlabs/fserver#39]
The release history feed throws the following warnings:
- Warning: get_class() expects parameter 1 to be object, string given in FeatureServerProjectXMLFormatter->render() (line 10 of fserver/fserver_services/fserver_services.inc).
- Warning: Unknown class passed as parameter in FeatureServerProjectXMLFormatter->render() (line 10 of fserver/fserver_services/fserver_services.inc).

**Comment by frederickjh** [comment]
The same error is present in coldfrontlabs/fserver#47

**Comment by minorOffense** [comment]
Closing as duplicate
