### ISSUE TITLE
 Many errors after installation

### ISSUE THREAD

**Issue by semyondragunov** [coldfrontlabs/fserver#45]
Install 7.x-1.x brach

All views -  Broken/missing handler

After create Release node - Notice: Undefined property: FserverRelease::$project_short_name in FserverRelease->generateReleaseName() (line 390 of /mnt/work/www/test/sites/all/modules/fserver/includes/fserver.entity.inc).

There is a working version for drupal 7?

**Comment by frederickjh** [comment]
If the notice on drupal.org is correct, then answer is no. However, see the note at the bottom.
From: <a href="https://www.drupal.org/project/fserver">https://www.drupal.org/project/fserver<a/>

<b>D7 Release</b>
Please dont use the D7 release, its pretty buggy yet and we dont have an active maintainer for the branch, which is already pretty far behind the patches on the D6 branch. I will consider completly removing the current D7 port, reinitiating it once again from the current D6 branch, if time comes / maintainer arrives.

<b>For now, you can also host D7 modules on a D6 based FServer!</b>
