### ISSUE TITLE
FserverRelease::$project_short_name

### ISSUE THREAD

**Issue by fugazi73** [coldfrontlabs/fserver#52]
I just test the new version and unfortunately I get an error. Only for information

Notice: Undefined property: FserverRelease::$project_short_name in FserverRelease->generateReleaseName() (line 564 of /sites/all/modules/fserver/includes/fserver.entity.inc).

**Comment by CptCasual** [comment]
I reproduced this error.

**Comment by CptCasual** [comment]
Fixed.
https://github.com/coldfrontlabs/fserver/pull/53
